# Generated by Django 6.0.1 on 2026-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('role_id', models.IntegerField()),
                ('area_id', models.IntegerField()),
            ],
        ),
    ]
