# Generated by Django 5.2.8 on 2026-01-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('delivery', 'Delivery Person')], default='user', max_length=20),
        ),
    ]
