# Generated by Django 6.0.1 on 2026-01-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260119_2114'),
    ]

    operations = [
    ]
