# Generated by Django 6.0.1 on 2026-02-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userregister_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='role',
        ),
    ]
